"""create tables

Revision ID: 59761d2c65a9
Revises: 
Create Date: 2026-03-08 15:50:39.070750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59761d2c65a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "packets",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("is_reserved", sa.Boolean(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "delivery_agent",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("is_reserved", sa.Boolean(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.execute(
        """
        INSERT INTO food (id, name)
        VALUES (1, 'Burger')
        """
    )

    # Insert packets (1–15)
    for i in range(1, 16):
        op.execute(
            f"""
            INSERT INTO packets (id, food_id, is_reserved)
            VALUES ({i}, 1, FALSE)
            """
        )

    # Insert delivery agents (1–10)
    for i in range(1, 11):
        op.execute(
            f"""
            INSERT INTO delivery_agent (id, is_reserved)
            VALUES ({i}, FALSE)
            """
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM packets WHERE id BETWEEN 1 AND 15")
    op.execute("DELETE FROM delivery_agent WHERE id BETWEEN 1 AND 10")
    op.execute("DELETE FROM food WHERE id = 1")

    op.drop_table("packets")
    op.drop_table("delivery_agent")
    op.drop_table("food")
    # ### end Alembic commands ###
